### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by RomanHodulak** [OndrejSodek/cvut-progtest-script#1]
Hello.
I've ran in to an interesting little issue. I've had in/out txt files from Linux machine and I ran progtest.sh on Windows. What happened was that progtest.sh printed FAILED! on all of the test cases, even though files and program output looked exactly the same.
I've examined the files from the Linux machine and the output of the program compiled and ran on Windows and noticed that only line-endings were different.

Adding `--strip-trailing-cr` to the `diff` commands in progtest.sh fixes the issue, so I suggest adding that to your script. What do you think?

**Comment by OndrejSodek** [comment]
Yeah, I guess it doesn't break anything.
Thanks for the suggestion.
