### ISSUE TITLE
Add "-Wno-deprecated" for new compilers

### ISSUE THREAD

**Issue by podruh** [OndrejSodek/cvut-progtest-script#3]
New clang throws warning about deprecated usage when compiling C file with C++ compiler.
compileOptionsDef and compileOptionsEasierDef should both have "-Wno-deprecated" option to eliminate this behavior.

**Comment by OndrejSodek** [comment]
Hi,

I don't really understand why clang would be an issue when the script uses g++/gcc.
Can you elaborate?

Also, I don't think the "-Wno-deprecated" option is about compiling C files with C++ compiler.
g++ manual says

>     -Wno-deprecated
>         Do not warn about usage of deprecated features.

I might be wrong, though.
